on: workflow_dispatch

jobs:
  rdf-export:
    runs-on: ubuntu-latest
    name: Test rdf export
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Export graph as RDF
        uses: logseq/rdf-export@main
        with:
          rdfFile: test-export.ttl

      - name: commit files
        run: |
          git config --local user.email "thomas.francart@sparna.fr"
          git config --local user.name "Thomas Francart"
          git add test-export.ttl
          git commit -m "test-export.ttl" -a --allow-empty
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
