on: workflow_dispatch

jobs:
  rdf-export:
    runs-on: ubuntu-latest
    name: Test rdf export
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Export graph as RDF
        uses: logseq/rdf-export@main
        with:
          rdfFile: test-export.ttl
          
      - uses: actions/upload-artifact@v3
        with:
          name: RDF export
          path: test-export.ttl
